### ISSUE TITLE
Make image slider functional on home page

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#10]
Just thought I'd flag this one :)

**Comment by deringer** [comment]
I... didn't notice the second slider layer in the Photoshop file :grin: 

I've added the second slides, but with some notes:

* I've had to remove the controls as they seem to jump up and down, depending on the height of the content in the text slider.
* In addition to that, if somebody was to click on one of the controls, the text slide would change, but not the adjacent image slide.

Leaving at this is the simple way of getting it done, however, if we need to have the controls there, we might have to look at making a single full width slider and setting the background image to include the red background and hope that the text doesn't spill over the red section. I'm pretty sure Divi will bring it's own complications with that regard.

**Comment by deringer** [comment]
With the split sliders, it seems that they can sometimes get out of sync as well.

**Comment by leah-wuttke** [comment]
This looks fine to me :)

**Comment by deringer** [comment]
Excellent!
