### ISSUE TITLE
Cafe page sub-heading styles and spacing

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#11]
Can we review the size of the sub-headings in the text sections on the cafe page? 
Can we also make it so the padding around the text is even within each container so the content is central(ish) to the box? - like the attached :)

![screen shot 2015-11-18 at 8 46 01 pm](https://cloud.githubusercontent.com/assets/15889892/11238440/8a0f6b6e-8e35-11e5-8f8f-ff802b126270.png)

**Comment by deringer** [comment]
@leah-wuttke FYI, each of the text sections have their own custom padding as the length of the text varies between each box. I'll do some tweaking to get the text to sit vertically centered.

**Comment by deringer** [comment]
Resolved by #14
