### ISSUE TITLE
Add 'Download Menu' button at top of Catering Page

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#12]
Underneath the introductory info on the catering page, can you add a button that says 'DOWNLOAD MENU'. I'll supply a PDF to download (I tried to do this myself... I wasn't successful! haha)

**Comment by deringer** [comment]
I've added the CTA button content and will push the change up to the staging site with other changes. I'll attach the PDF there when supplied.

**Comment by leah-wuttke** [comment]
I've uploaded a PDF. Can you check that the URL that I attached is correct and will work when you make the site live?

**Comment by deringer** [comment]
Perfect - the URL will change to foodsforlife.com.au when we go live :+1:
