### ISSUE TITLE
Page Header and Intro Copy Styling

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#16]
Can we please adjust page headers and intro copy as per attached PDF example. 
[Page Headers and Intro Copy.pdf](https://github.com/deringer/foods-for-life/files/41436/Page.Headers.and.Intro.Copy.pdf)

**Comment by leah-wuttke** [comment]
Just on this, each heading has tracking value of 20, so if we can just 'open' the letterspacing just a smidge, that would be great - as well as increasing the copy size.

**Comment by deringer** [comment]
Resolved in 81825ac
