### ISSUE TITLE
Home Page: Image/section responsiveness

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#18]
I know you mentioned that there may be issues with this, but can the responsiveness of this be fixed (see attached)? Or is this something you'll look at once everything is pretty much done? ... just checking :)
![screen shot 2015-11-23 at 7 50 32 pm](https://cloud.githubusercontent.com/assets/15889892/11333813/5ef23c6a-9220-11e5-9186-71faefd00d76.png)
![screen shot 2015-11-23 at 7 50 25 pm](https://cloud.githubusercontent.com/assets/15889892/11333814/5ef4f50e-9220-11e5-9360-18096af2597c.png)

**Comment by deringer** [comment]
I've fixed the width of the boxed layout of the site so that you won't see that spreading anymore.

Divi's theme customiser allows you to set a custom value for the boxed layout width, which looks to be overridden when using vertical navigation.
