### ISSUE TITLE
Specials: Filtering

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#19]
I noticed when you select one of the categories on the Specials page, the menu disappears and a weird dropdown appears? Can you let me know what this is or if there is a way to make the 'category' menu on the right stay visible? (see attached for example of what happens after selecting Vitamins & Supplements)
![specials - filter screen reference](https://cloud.githubusercontent.com/assets/15889892/11333874/db714f1a-9220-11e5-881b-027e84bc8029.png)

**Comment by deringer** [comment]
This is the sorting provided by the WooCommerce plugin we're using for the 'shopfront'. It has a rabbit hole of templates and nested functions to dig through to locate update this display. But it's a default.

I'll see if I can track down the appropriate one and add the sidebar to it.

**Comment by deringer** [comment]
Alright, turns out I made a bigger deal out of that than what it was!
