### ISSUE TITLE
Increase 'top' padding above first row thumbnails on Health Foods index page

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#27]
Can we increase the top padding above the thumbnails on the Health Foods 'index' page to be more even (i.e. about equal to the padding on the left and right of the section). If it can be similar at the bottom too that would be good too - see attached.
![screen shot 2015-11-25 at 11 10 56 pm](https://cloud.githubusercontent.com/assets/15889892/11397521/12f96c42-93ca-11e5-808c-569d56732b45.png)

**Comment by deringer** [comment]
Done!

Let me know if [this](http://ffl.dev.iatstuti.net/health-foods/) is ok :)

**Comment by deringer** [comment]
Done!

Let me know if [this](http://ffl.dev.iatstuti.net/health-foods/) is ok :)

**Comment by leah-wuttke** [comment]
Perfect :)
