### ISSUE TITLE
Review in text link colour styling on Health Food pages

### ISSUE THREAD

**Issue by leah-wuttke** [deringer/foods-for-life#28]
I've added a section under the logos on each of the Health Food subpages. Can we change the active link colour/weight on this 'light' background? I'm happy with it being underlined, or red and bold... whatever is easiest. This will occur across all these sub pages - see attached
![screen shot 2015-11-25 at 11 14 48 pm](https://cloud.githubusercontent.com/assets/15889892/11397619/c25ff1ba-93ca-11e5-91db-2b810ed2ffd8.png)
.

**Comment by deringer** [comment]
Resolved by 84a63d6
