### ISSUE TITLE
Create 'about' page

### ISSUE THREAD

**Issue by deringer** [deringer/foods-for-life#3]

**Comment by leah-wuttke** [comment]
I've populated the about page with some content. Are you able to make the body copy next to the photo (in the body of the page) smaller and more along the size of the text in the calls to action on the bottom of the cafe and health food pages?

**Comment by deringer** [comment]
The row that that text is in had the subheading class attached to it (I assume you copied the row above it?). Anyway, that was hijacking the font size. I've fixed it now.
