### ISSUE TITLE
Add social icons to main navigation

### ISSUE THREAD

**Issue by deringer** [deringer/foods-for-life#6]

**Comment by deringer** [comment]
@leah-wuttke - I don't suppose that you have the links to all their different social media platforms so that I can get this done?

**Comment by leah-wuttke** [comment]
Hmmm... not yet. I'll follow up with them early this week.

**Comment by leah-wuttke** [comment]
I'm going through this with Jason tomorrow (it was on his list he sent me), so I'll have something for you then :)

**Comment by leah-wuttke** [comment]
I don't have a link for 'We Chat'. Will have to follow this up. For the interim, maybe just direct to the site. See links below:

Facebook: https://www.facebook.com/FoodsforLifeGawlerPlace/
Twitter: https://twitter.com/FoodsForLife1
Instagram: https://www.instagram.com/foodsforlife_adl/
WeChat: https://web.wechat.com/
